### ISSUE TITLE
Outdated version referenced in site docs

### ISSUE THREAD

**Issue by mcrumm** [muxinc/mux-elixir#21]
Hi, Mux! First, thanks so much for building a first-class Elixir package! ❤️ 

The version listed in the [Elixir SDK docs](https://mux.com/for/elixir/) could use an update, though :)

I wasn't sure the best place to call this out, so I hope you don't mind my doing so here. Thanks, again!

```diff
def deps do
  [
-    {:mux, "~> 1.4.0"}
+    {:mux, "~> 1.8.0"}
  ]
end

**Comment by mmcc** [comment]
Awesome, thank you so much for the heads up! Just pushed an update, should be deployed soon. We really should automate that 🤔
