### ISSUE TITLE
Dialyzer reports pattern_match error using Mux.Video.Uploads.create/2

### ISSUE THREAD

**Issue by mrcasals** [muxinc/mux-elixir#29]
Hi!

At a project we're using Mux to upload videos. We're using `mux` version 2.0.0 and `tesla` 1.4.1, both versions are the latest released in HexPM. Before opening this issue, I forced a recompilation of mux, tesla and their dependencies with `mix deps.compile mux tesla --include-children` and then retried it without the `--include-children` flag just in case.

Here's the code:

```elixir
case Mux.Video.Uploads.create(client, params) do
  {:ok, metadata, _client} ->
    {:ok, %{upload_url: metadata["url"]}}

  {:error, _, errors} ->
    {:error, "Couldn't create upload URL: #{Enum.join(errors, ", ")}"}
end
```

But dialyzer is complaining about the types when matching the result:

```
The pattern can never match the type.

Pattern:
{:ok, _metadata, __client}

Type:

  {:error, _}
  | {:ok,
     %Tesla.Env{
       :__client__ => %Tesla.Client{
         :adapter => nil | {_, _} | {_, _, _},
         :fun => _,
         :post => [any()],
         :pre => [any()]
       },
       :__module__ => atom(),
       :body => _,
       :headers => [{_, _}],
       :method => :delete | :get | :head | :options | :patch | :post | :put | :trace,
       :opts => [{_, _}],
       :query => [{_, _}],
       :status => nil | integer(),
       :url => binary()
     }}
```

```
The pattern can never match the type.

Pattern:
{:error, _, _errors}

Type:

  {:error, _}
  | {:ok,
     %Tesla.Env{
       :__client__ => %Tesla.Client{
         :adapter => nil | {_, _} | {_, _, _},
         :fun => _,
         :post => [any()],
         :pre => [any()]
       },
       :__module__ => atom(),
       :body => _,
       :headers => [{_, _}],
       :method => :delete | :get | :head | :options | :patch | :post | :put | :trace,
       :opts => [{_, _}],
       :query => [{_, _}],
       :status => nil | integer(),
       :url => binary()
     }}
```

Docs and tests for the `Mux.Video.Uploads.create/2` function do not mention what happens when there's an error, so we had to manually check (**it'd be nice to have tests for that**). But they do mention the result when the call is successful, and it returns a tuple with 3 elements:

https://github.com/muxinc/mux-elixir/blob/ab11146d47c70564fd6b00c236c4e9c56d798a61/lib/mux/video/uploads.ex#L15-L27

Instead of that, dialyzer reports that it returns a tuple with 2 elements.

Have you encountered this issue before?

This is affecting our CI pipeline, because we have a step checking that the dialyzer returns OK, but we had to ignore these errors manually:

```
# .dialyzer_ignore.exs
[
  {"lib/politic_all/mux.ex", :no_return},
  {"lib/politic_all/mux.ex", :pattern_match}
]
```

**Comment by mmcc** [comment]
Hi there, you're totally right, the error case deserves more documentation + tests. Ultimately this library is a pretty thin wrapper around a Tesla base client, so we should make some of those references a bit more explicit. 

On successful requests there's a [middleware](https://github.com/muxinc/mux-elixir/blob/master/lib/mux/middleware/simplify_response.ex) that pops off the body to make it a little easier to interact with (hence the 3 item tuple), but otherwise the return value should just be the `Tesla.Env.result/0` you'd expect from [Tesla](https://hexdocs.pm/tesla/Tesla.Env.html#t:result/0). It looks like Dialyzer is just expecting the base Tesla result and (reasonably so) doesn't know about the middleware, so we'll take a look at improving that next week.

**Comment by mrcasals** [comment]
@mmcc thanks, that would be useful! 😄

**Comment by mrcasals** [comment]
Hi @mmcc! Did you find time to work on that? I need to work on our Mux integration again and the error pops up again 😄

**Comment by mrcasals** [comment]
The same error is happening when using `Mux.Video.Assets.delete/2`. In addition, in this case the documentation seems to be contradictory:

https://github.com/muxinc/mux-elixir/blob/116239ee569d21622177d132137bdafe719ac6b1/lib/mux/video/assets.ex#L59-L74

(notice how the docs mention a 2-elemnt tuple, but the code examples show a 3-elements one)

**Comment by mrcasals** [comment]
According to https://github.com/teamon/tesla/issues/483, the Mux middleware is at fault since it doesn't comply with the expected type. Thus, it's not composable.

The issue has a code example by the library owner showing how to approach this (basically, merging what you want into the 2nd element of the response in `Tesla.run/2`). Adding this would imply a change in the API of the `mux-elixir` library, so it would require a bump to a major version IMO. 

I'll try to get a PR for those changes!

**Comment by mrcasals** [comment]
You can find a PR in #32! 😄
