### ISSUE TITLE
Support signing for Spaces

### ISSUE THREAD

**Issue by philcluff** [muxinc/mux-elixir#47]
Currently the signing utilities in mux-elixir only support Playback IDs. 

Proposed steps to match [the change we made in mux-node-sdk](https://github.com/muxinc/mux-node-sdk/pull/199): 
* Split `sign` into `sign_playback_id` and `sign_space_id`
* Make `sign` an alias to `sign_playback_id` and mark it as deprecated
* Release etc.

It'd also be good to add a signing example to the README.md

**Comment by ndan** [comment]
Looks like it's done, except:

> It'd also be good to add a signing example to the README.md

I would suggest to close the issue
